name: cc2p
base: core22
version: '0.3.7'
title: cc2p
summary: Convert CSV To Parquet
description: |
  **CC2P** is a Rust-based project designed to convert CSV files in a selected folder into Parquet format. This tool offers a simple and efficient way to handle and convert your CSV data files.

  ## Features

  - **Fast and reliable CSV to Parquet conversion**: Ensures high performance and accuracy in converting CSV files to Parquet format.
  - **Multithreaded processing**: Utilizes the power of the `tokio` crate to enable concurrent processing, enhancing conversion speed.
  - **Progress indication**: Tracks and displays conversion progress using the `indicatif` crate, providing real-time feedback on the process.

website: https://rayyildiz.com/projects/cc2p/
source-code: https://github.com/rayyildiz/cc2p
issues: https://github.com/rayyildiz/cc2p/issues/new

architectures:
  - build-on: amd64
grade: stable

confinement: strict
parts:
  cc2p:
    plugin: rust
    source: .



apps:
  cc2p:
    command: bin/cc2p

