name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        include:
          - toolchain: 1.80.0
          - toolchain: stable
          - toolchain: beta
          - toolchain: nightly

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      - run: cargo install cargo-tarpaulin

      - run: cargo test

      - run: cargo tarpaulin -o html
